In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
import math
import re

In [2]:
df = pd.read_csv("traffic.csv")
print(df.shape)
df.head()

(17544, 863)

,Date,0,1,2,3,4,5,6,7,8,...,852,853,854,855,856,857,858,859,860,861
0,2015-01-01 00:00:00,0.0048,0.0146,0.0289,0.0142,0.0064,0.0232,0.0162,0.0242,0.0341,...,0.0051,0.0051,0.0074,0.0079,0.0051,0.0051,0.0339,0.0051,0.0100,0.0121
1,2015-01-01 01:00:00,0.0072,0.0148,0.0350,0.0174,0.0084,0.0240,0.0201,0.0338,0.0434,...,0.0036,0.0036,0.0107,0.0058,0.0036,0.0036,0.0348,0.0036,0.0087,0.0136
2,2015-01-01 02:00:00,0.0040,0.0101,0.0267,0.0124,0.0049,0.0170,0.0127,0.0255,0.0332,...,0.0030,0.0030,0.0043,0.0050,0.0030,0.0030,0.0327,0.0030,0.0061,0.0107
3,2015-01-01 03:00:00,0.0039,0.0060,0.0218,0.0090,0.0029,0.0118,0.0088,0.0163,0.0211,...,0.0033,0.0033,0.0019,0.0052,0.0033,0.0033,0.0292,0.0033,0.0040,0.0071
4,2015-01-01 04:00:00,0.0042,0.0055,0.0191,0.0082,0.0024,0.0095,0.0064,0.0087,0.0144,...,0.0049,0.0049,0.0011,0.0071,0.0049,0.0049,0.0264,0.0049,0.0040,0.0039

In [8]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,852,853,854,855,856,857,858,859,860,861
count,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,...,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000,17544.000000
mean,0.049324,0.046016,0.105870,0.056633,0.026812,0.056526,0.062885,0.060598,0.062839,0.076275,...,0.017752,0.021159,0.025893,0.035347,0.023338,0.025883,0.039669,0.043058,0.029241,0.031537
std,0.062469,0.048398,0.082205,0.036746,0.035872,0.066524,0.061002,0.054689,0.043479,0.093617,...,0.013580,0.013271,0.020939,0.022303,0.014115,0.016802,0.018035,0.023567,0.017606,0.019453
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.008900,0.018100,0.035600,0.026800,0.007875,0.013900,0.020000,0.021100,0.025400,0.016600,...,0.005800,0.007900,0.006500,0.022300,0.009600,0.010700,0.027600,0.027800,0.014100,0.012500
50%,0.046300,0.036800,0.081000,0.060000,0.019000,0.041800,0.048200,0.055000,0.059500,0.055500,...,0.013900,0.021900,0.026500,0.035500,0.025900,0.028700,0.042100,0.041200,0.031800,0.034100
75%,0.059900,0.053700,0.175500,0.074700,0.024300,0.055400,0.072500,0.073700,0.081500,0.084800,...,0.030500,0.031600,0.040000,0.044000,0.033400,0.037200,0.054000,0.063800,0.039300,0.046700
max,0.474700,0.450000,0.420100,0.494700,0.406900,0.510100,0.362000,0.492500,0.366400,0.698300,...,0.122600,0.087600,0.342000,0.555500,0.288900,0.397500,0.141900,0.353200,0.415900,0.217400

In [9]:
df.agg("mean", axis="columns")
# df.agg(x=('A', 'max'), y=('B', 'min'), z=('C', 'mean'))

TypeError: can only concatenate str (not "float") to str

In [10]:
df1 = pd.read_csv("googleplaystore.csv")
print(df1.shape)
df1.head()

(10841, 13)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite â€“ FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [11]:
df2 = pd.read_csv("googleplaystore_user_reviews.csv")
print(df2.shape)
df2.head()

(64295, 5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [15]:
df1.groupby("Android Ver").count()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver
Android Ver,,,,,,,,,,,,
1.0 and up,2,2,2,2,2,2,2,2,2,2,2,2
1.5 and up,20,20,16,20,20,20,20,20,20,20,20,19
1.6 and up,116,116,87,116,116,116,116,116,116,116,116,115
2.0 and up,32,32,27,32,32,32,32,32,32,32,32,31
2.0.1 and up,7,7,7,7,7,7,7,7,7,7,7,7
2.1 and up,134,134,113,134,134,134,134,134,134,134,134,134
2.2 - 7.1.1,1,1,0,1,1,1,1,1,1,1,1,1
2.2 and up,244,244,208,244,244,244,244,244,244,244,244,244
2.3 and up,652,652,582,652,652,652,652,652,652,652,652,651
2.3.3 and up,281,281,240,281,281,281,281,281,281,281,281,281
3.0 and up,241,241,211,241,241,241,241,241,241,241,241,240
3.1 and up,10,10,8,10,10,10,10,10,10,10,10,10
3.2 and up,36,36,31,36,36,36,36,36,36,36,36,36
4.0 and up,1375,1375,1131,1375,1375,1375,1375,1375,1375,1375,1375,1373
4.0.3 - 7.1.1,2,2,2,2,2,2,2,2,2,2,2,2
4.0.3 and up,1501,1501,1240,1501,1501,1501,1501,1501,1501,1501,1501,1501
4.1 - 7.1.1,1,1,1,1,1,1,1,1,1,1,1,1
4.1 and up,2451,2451,2059,2451,2451,2451,2451,2451,2451,2451,2451,2451
4.2 and up,394,394,338,394,394,394,394,394,394,394,394,393
4.3 and up,243,243,207,243,243,243,243,243,243,243,243,243
4.4 and up,980,980,875,980,980,980,980,980,980,980,980,980
4.4W and up,12,12,6,12,12,12,12,12,12,12,12,12
5.0 - 6.0,1,1,1,1,1,1,1,1,1,1,1,1
5.0 - 7.1.1,1,1,0,1,1,1,1,1,1,1,1,1
5.0 - 8.0,2,2,2,2,2,2,2,2,2,2,2,2
5.0 and up,601,601,535,601,601,601,601,601,601,601,601,601
5.1 and up,24,24,18,24,24,24,24,24,24,24,24,24
6.0 and up,60,60,48,60,60,60,60,60,60,60,60,60
7.0 - 7.1.1,1,1,1,1,1,1,1,1,1,1,1,1
7.0 and up,42,42,41,42,42,42,42,42,42,42,42,42
7.1 and up,3,3,3,3,3,3,3,3,3,3,3,3
8.0 and up,6,6,5,6,6,6,6,6,6,6,6,6
Varies with device,1362,1362,1319,1362,1362,1362,1361,1362,1362,1362,1362,1362